"""Removed price column

Revision ID: 078505ddf451
Revises: 
Create Date: 2020-03-29 19:36:03.072034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '078505ddf451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
