"""Restore price column

Revision ID: 4d1e3cd2d723
Revises: 078505ddf451
Create Date: 2020-03-29 20:02:35.023163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1e3cd2d723'
down_revision = '078505ddf451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', postgresql.MONEY(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
